            - name: Download GitHub Release
  # You may pin to the exact commit or the version.
  # uses: Legion2/download-release-action@68df3d242858e28a7e6d8b9838a3e6730cdfc422
  uses: Legion2/download-release-action@v2.1.0
  with:
    # The repository from where to download the files.
Given as "Weak Aura Update"

    repository: 
    # The version tag of the release
    tag: 
    # The file which should be downloaded.
If not specified download the source code. 

    file: # optional
    # download directory
    path: # optional, default is ./
    # Github token to access private repositories
    token: # optional
